# This is a config for E2B sandbox template.
# You can use template ID (hy7jqofnt8lu4tr9u8q7) or template name (lovable-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-test')

team_id = "552be8bd-48de-48c6-acce-9b6e20f2028e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-test"
template_id = "hy7jqofnt8lu4tr9u8q7"
